server:
  port: 8085

spring:
  application:
    name: as222s5_t09_be
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

RAPIDAPI_KEY: ${RAPIDAPI_KEY}
